# Language redirects.
[[redirects]]
from = "/"
to = "/ru/"
status = 302
force = true
conditions = {Language = ["ru"]}
[[redirects]]
from = "/"
to = "/en/"
status = 302
force = true

# Old blog article redirects.
[[redirects]]
from = "/2009/07/iptables-router-performance.html"
to = "/en/posts/2009/iptables-router-performance/"
status = 301
force = true
[[redirects]]
from = "/2008/11/monit-lightweight-monitoring-solution.html"
to = "/en/posts/2008/monit-lightweight-monitoring-solution/"
status = 301
force = true
[[redirects]]
from = "/2010/02/7-java-heap.html"
to = "/ru/posts/2010/7-java-heap/"
status = 301
force = true
[[redirects]]
from = "/2010/01/swap.html"
to = "/ru/posts/2010/swap/"
status = 301
force = true
[[redirects]]
from = "/2009/05/nginx-2.html"
to = "/ru/posts/2009/nginx-2/"
status = 301
force = true
[[redirects]]
from = "/2013/04/nginx-1.html"
to = "/ru/posts/2013/nginx-1/"
status = 301
force = true
[[redirects]]
from = "/2009/03/gnunet.html"
to = "/ru/posts/2009/gnunet/"
status = 301
force = true
[[redirects]]
from = "/2009/03/denyhosts-ssh.html"
to = "/ru/posts/2009/denyhosts-ssh/"
status = 301
force = true
[[redirects]]
from = "/2009/02/apache.html"
to = "/ru/posts/2009/apache/"
status = 301
force = true
[[redirects]]
from = "/2008/12/linux.html"
to = "/ru/posts/2008/linux/"
status = 301
force = true
[[redirects]]
from = "/2008/12/gnu-screen.html"
to = "/ru/posts/2008/gnu-screen/"
status = 301
force = true
[[redirects]]
from = "/2008/12/vi.html"
to = "/ru/posts/2008/vi/"
status = 301
force = true
[[redirects]]
from = "/2008/12/blog-post.html"
to = "/ru/posts/2008/blog-post/"
status = 301
force = true
[[redirects]]
from = "/2008/11/monit.html"
to = "/ru/posts/2008/monit/"
status = 301
force = true
[[redirects]]
from = "/2008/11/blog-post.html"
to = "/ru/posts/2008/change-case/"
status = 301
force = true
[[redirects]]
from = "/2008/10/openvpn-vpn-http-https.html"
to = "/ru/posts/2008/openvpn-vpn-http-https/"
status = 301
force = true
[[redirects]]
from = "/2008/10/blog-post.html"
to = "/ru/posts/2008/change-password-on-login/"
status = 301
force = true
[[redirects]]
from = "/2008/08/bash.html"
to = "/ru/posts/2008/bash/"
status = 301
force = true
[[redirects]]
from = "/2008/08/man-crontab.html"
to = "/ru/posts/2008/man-crontab/"
status = 301
force = true

[build]
  base    = ""
  publish = "output"
  command = "nikola build"
